blank_issues_enabled: false
contact_links:
  - name: Support Server
    url: https://discord.gg/GF67PwqsMb
    about: Please ask general client questions here, as the issue tracker is reserved for bug reports and feature requests.
